apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cloud
spec:
  clusterIP: None
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  - name: vttablet
    port: 3380
    targetPort: vttablet
  - name: vttablet-grpc
    port: 14999
    targetPort: vttablet-grpc
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: cloud
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      hostname: mysql
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: passw0rd
        - name: MYSQL_DATABASE
          value: peak
        image: percona/percona-server:5.7
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        args:
          - --log_bin=ON
          - --server-id=1126369102
          - --gtid-mode=ON
          - --enforce-gtid-consistency=ON
      - name: vttablet
        image: serhatcetinkaya/vitess:60322344f-lite
        imagePullPolicy: IfNotPresent
        command:
          - /vt/bin/vttablet
          - -topo_implementation
          - consul
          - -topo_global_server_address
          - localhost:8500
          - -topo_global_root
          - vitess/global
          - -tablet-path
          - us_east_1-1126369102
          - -db_host
          - mysql
          - -db_port
          - "3306"
          - -client-found-rows-pool-size
          - "400"
          - -queryserver-config-pool-size
          - "400"
          - -queryserver-config-transaction-cap
          - "400"
          - -db_dba_user
          - root
          - -db_dba_password
          - passw0rd
          - -db_app_user
          - root
          - -db_app_password
          - passw0rd
          - -db_filtered_user
          - root
          - -db_filtered_password
          - passw0rd
          - -db_repl_user
          - root
          - -db_repl_password
          - passw0rd
          - -enforce_strict_trans_tables=True
          - -init_keyspace
          - peak-test
          - -init_shard
          - "0"
          - -init_tablet_type
          - replica
          - -init_db_name_override
          - peak
          - -vtctld_addr
          - vtctld:15999
          - -enable_replication_reporter
          - -health_check_interval
          - 5s
          - -service_map
          - grpc-queryservice,grpc-tabletmanager,grpc-updatestream
          - -grpc_port
          - "14999"
          - -port
          - "3380"
          - -disable_active_reparents
          - -unhealthy_threshold
          - 86400s
          - -db_charset
          - utf8mb4
          - -grpc_max_message_size
          - "37754432"
          - -queryserver-config-max-result-size
          - "10000"
          - -init_populate_metadata
        ports:
        - containerPort: 3380
          name: vttablet
        - containerPort: 14999
          name: vttablet-grpc
      - image: nginx:1.17.7
        imagePullPolicy: IfNotPresent
        name: nginx
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/consul.conf
          name: nginx-config-vol
          subPath: consul.conf
      volumes:
      - configMap:
          name: nginx-config
        name: nginx-config-vol